<?xml version="1.0"?>

<package format="3">

  <name>
    spotarm_servo_gamepad
  </name>

  <version>
    0.1.0
  </version>

  <description>
    MoveIt Servo gamepad controller for the SPOT robot arm.
  </description>

  <maintainer email="msd@example.com">
    msd
  </maintainer>

  <license>
    Apache-2.0
  </license>


  <buildtool_depend>
    ament_python
  </buildtool_depend>


  <exec_depend>
    rclpy
  </exec_depend>

  <exec_depend>
    sensor_msgs
  </exec_depend>

  <exec_depend>
    geometry_msgs
  </exec_depend>

  <exec_depend>
    std_srvs
  </exec_depend>

  <exec_depend>
    joy
  </exec_depend>

  <exec_depend>
    moveit_servo
  </exec_depend>

  <exec_depend>
    moveit_configs_utils
  </exec_depend>

  <exec_depend>
    robot_moveit_config
  </exec_depend>


  <export>

    <build_type>
      ament_python
    </build_type>

  </export>

</package>
